name = "MidJourney API"
version = "0.0.3"
usage = "When you have a midjourney prompt and need to create an image from it and display images from local path"
content_type = "api"
content_api = """
""\"
The following functions are the MidJourney API. Always prefer this to other discord libraries and access methods.
""\"


from midjourney import MidJourneyAPI
from typing import List


def create_image(prompt: str) -> List[str]:
    ""\"
    This will wait for images to be generated and download them for display.

    Example usage:

    ```python
    create_image('Wild boar --ar 1:1') # do not add "/imagine prompt:" at the beginning
    ```
    ""\"
    midjourney = MidJourneyAPI()
    return midjourney.create_image(prompt)
"""
